source 'http://rubygems.org'
ruby '2.7.4'
gem 'browser'
gem 'cucumber', '3.1.2'
gem 'parallel_tests', '2.29.0'
gem 'rake'
gem 'require_all', '~> 1.3.3'
gem 'rspec'
gem 'rspec-expectations', '~> 3.3.0'
gem 'rubocop'
gem 'selenium-webdriver',         '3.141'
gem 'rest-client',                '~> 2.0'
